using System.Collections.Generic;

namespace GribSharp.Tables
{
    /// <summary>
    /// Tablas de código GRIB2 (WMO + locales NCEP), según la documentación NCEP
    /// (https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/). Cubre la Tabla 0.0
    /// (disciplinas), 4.0 (plantillas de producto), 4.1 (categorías) y 4.2 (parámetros)
    /// para las disciplinas atmosféricas, de superficie y oceánicas de uso habitual.
    /// Cualquier (discipline, category, number) no listado se resuelve con un nombre
    /// genérico, de modo que TODA variable se parsea sin excepción.
    /// </summary>
    public static class CodeTables
    {
        // Tabla 4.2 - Parámetro por disciplina/categoría. Clave (disciplina, categoría, número).
        private static readonly Dictionary<(int, int, int), (string, string)> Params =
            new Dictionary<(int, int, int), (string, string)>
            {
                // === Disciplina 0 - Meteorología ===
                // Categoría 0: Temperatura
                { (0, 0, 0), ("Temperature", "K") },
                { (0, 0, 1), ("Virtual temperature", "K") },
                { (0, 0, 2), ("Potential temperature", "K") },
                { (0, 0, 3), ("Pseudo-adiabatic potential temperature", "K") },
                { (0, 0, 4), ("Maximum temperature", "K") },
                { (0, 0, 5), ("Minimum temperature", "K") },
                { (0, 0, 6), ("Dewpoint temperature", "K") },
                { (0, 0, 7), ("Dewpoint depression", "K") },
                { (0, 0, 8), ("Lapse rate", "K/m") },
                { (0, 0, 9), ("Temperature anomaly", "K") },
                { (0, 0, 10), ("Latent heat net flux", "W/m^2") },
                { (0, 0, 11), ("Sensible heat net flux", "W/m^2") },
                { (0, 0, 12), ("Heat index", "K") },
                { (0, 0, 13), ("Wind chill factor", "K") },
                { (0, 0, 14), ("Minimum dewpoint depression", "K") },
                { (0, 0, 15), ("Virtual potential temperature", "K") },
                { (0, 0, 16), ("Snow phase change heat flux", "W/m^2") },
                { (0, 0, 17), ("Skin temperature", "K") },
                { (0, 0, 18), ("Snow temperature (top of snow)", "K") },
                { (0, 0, 19), ("Turbulent transfer coefficient for heat", "numeric") },
                { (0, 0, 20), ("Turbulent diffusion coefficient for heat", "m^2/s") },
                { (0, 0, 21), ("Apparent temperature", "K") },
                { (0, 0, 22), ("Temperature tendency due to short-wave radiation", "K/s") },
                { (0, 0, 23), ("Temperature tendency due to long-wave radiation", "K/s") },
                { (0, 0, 24), ("Temperature tendency due to short-wave radiation, clear sky", "K/s") },
                { (0, 0, 25), ("Temperature tendency due to long-wave radiation, clear sky", "K/s") },
                { (0, 0, 26), ("Temperature tendency due to parameterizations", "K/s") },
                { (0, 0, 27), ("Wet-bulb temperature", "K") },
                { (0, 0, 28), ("Unbalanced component of temperature", "K") },
                { (0, 0, 29), ("Temperature advection", "K/s") },
                { (0, 0, 30), ("Latent heat net flux due to evaporation", "W/m^2") },
                { (0, 0, 31), ("Latent heat net flux due to sublimation", "W/m^2") },
                { (0, 0, 32), ("Wet-bulb potential temperature", "K") },
                { (0, 0, 192), ("Snow phase change heat flux", "W/m^2") },
                { (0, 0, 193), ("Temperature tendency by all radiation", "K/s") },
                { (0, 0, 194), ("Relative error variance", "numeric") },
                { (0, 0, 195), ("Large scale condensate heating rate", "K/s") },
                { (0, 0, 196), ("Deep convective heating rate", "K/s") },
                { (0, 0, 197), ("Total downward heat flux at surface", "W/m^2") },
                { (0, 0, 198), ("Temperature tendency by all physics", "K/s") },
                { (0, 0, 199), ("Temperature tendency by non-radiation physics", "K/s") },
                { (0, 0, 200), ("Standard dev. of IR temp. over 1x1 deg. area", "K") },
                { (0, 0, 201), ("Shallow convective heating rate", "K/s") },
                { (0, 0, 202), ("Vertical diffusion heating rate", "K/s") },
                { (0, 0, 203), ("Potential temperature at top of viscous sublayer", "K") },
                { (0, 0, 204), ("Tropical cyclone heat potential", "J/m^2/K") },
                { (0, 0, 205), ("Effective layer (EL) temperature", "C") },
                { (0, 0, 206), ("Wet bulb globe temperature", "K") },

                // Categoría 1: Humedad
                { (0, 1, 0), ("Specific humidity", "kg/kg") },
                { (0, 1, 1), ("Relative humidity", "%") },
                { (0, 1, 2), ("Humidity mixing ratio", "kg/kg") },
                { (0, 1, 3), ("Precipitable water", "kg/m^2") },
                { (0, 1, 4), ("Vapor pressure", "Pa") },
                { (0, 1, 5), ("Saturation deficit", "Pa") },
                { (0, 1, 6), ("Evaporation", "kg/m^2") },
                { (0, 1, 7), ("Precipitation rate", "kg/m^2/s") },
                { (0, 1, 8), ("Total precipitation", "kg/m^2") },
                { (0, 1, 9), ("Large-scale precipitation (non-convective)", "kg/m^2") },
                { (0, 1, 10), ("Convective precipitation", "kg/m^2") },
                { (0, 1, 11), ("Snow depth", "m") },
                { (0, 1, 12), ("Snowfall rate water equivalent", "kg/m^2/s") },
                { (0, 1, 13), ("Water equivalent of accumulated snow depth", "kg/m^2") },
                { (0, 1, 14), ("Convective snow", "kg/m^2") },
                { (0, 1, 15), ("Large-scale snow", "kg/m^2") },
                { (0, 1, 16), ("Snow melt", "kg/m^2") },
                { (0, 1, 17), ("Snow age", "day") },
                { (0, 1, 18), ("Absolute humidity", "kg/m^3") },
                { (0, 1, 19), ("Precipitation type", "code table") },
                { (0, 1, 20), ("Integrated liquid water", "kg/m^2") },
                { (0, 1, 21), ("Condensate", "kg/kg") },
                { (0, 1, 22), ("Cloud mixing ratio", "kg/kg") },
                { (0, 1, 23), ("Ice water mixing ratio", "kg/kg") },
                { (0, 1, 24), ("Rain mixing ratio", "kg/kg") },
                { (0, 1, 25), ("Snow mixing ratio", "kg/kg") },
                { (0, 1, 26), ("Horizontal moisture convergence", "kg/kg/s") },
                { (0, 1, 27), ("Maximum relative humidity", "%") },
                { (0, 1, 28), ("Maximum absolute humidity", "kg/m^3") },
                { (0, 1, 29), ("Total snowfall", "m") },
                { (0, 1, 30), ("Precipitable water category", "code table") },
                { (0, 1, 31), ("Hail", "m") },
                { (0, 1, 32), ("Graupel", "kg/kg") },
                { (0, 1, 33), ("Categorical rain", "code table") },
                { (0, 1, 34), ("Categorical freezing rain", "code table") },
                { (0, 1, 35), ("Categorical ice pellets", "code table") },
                { (0, 1, 36), ("Categorical snow", "code table") },
                { (0, 1, 37), ("Convective precipitation rate", "kg/m^2/s") },
                { (0, 1, 38), ("Horizontal moisture divergence", "kg/kg/s") },
                { (0, 1, 39), ("Percent frozen precipitation", "%") },
                { (0, 1, 40), ("Potential evaporation", "kg/m^2") },
                { (0, 1, 41), ("Potential evaporation rate", "W/m^2") },
                { (0, 1, 42), ("Snow cover", "%") },
                { (0, 1, 43), ("Rain fraction of total cloud water", "proportion") },
                { (0, 1, 44), ("Rime factor", "numeric") },
                { (0, 1, 45), ("Total column integrated rain", "kg/m^2") },
                { (0, 1, 46), ("Total column integrated snow", "kg/m^2") },
                { (0, 1, 47), ("Large scale water precipitation (non-convective)", "kg/m^2") },
                { (0, 1, 48), ("Convective water precipitation", "kg/m^2") },
                { (0, 1, 49), ("Total water precipitation", "kg/m^2") },
                { (0, 1, 50), ("Total snow precipitation", "kg/m^2") },
                { (0, 1, 51), ("Total column water", "kg/m^2") },
                { (0, 1, 52), ("Total precipitation rate", "kg/m^2/s") },
                { (0, 1, 53), ("Total snowfall rate water equivalent", "kg/m^2/s") },
                { (0, 1, 54), ("Large scale precipitation rate", "kg/m^2/s") },
                { (0, 1, 55), ("Convective snowfall rate water equivalent", "kg/m^2/s") },
                { (0, 1, 56), ("Large scale snowfall rate water equivalent", "kg/m^2/s") },
                { (0, 1, 57), ("Total snowfall rate", "m/s") },
                { (0, 1, 58), ("Convective snowfall rate", "m/s") },
                { (0, 1, 59), ("Large scale snowfall rate", "m/s") },
                { (0, 1, 60), ("Snow depth water equivalent", "kg/m^2") },
                { (0, 1, 61), ("Snow density", "kg/m^3") },
                { (0, 1, 62), ("Snow evaporation", "kg/m^2") },
                { (0, 1, 64), ("Total column integrated water vapor", "kg/m^2") },
                { (0, 1, 65), ("Rain precipitation rate", "kg/m^2/s") },
                { (0, 1, 66), ("Snow precipitation rate", "kg/m^2/s") },
                { (0, 1, 67), ("Freezing rain precipitation rate", "kg/m^2/s") },
                { (0, 1, 68), ("Ice pellets precipitation rate", "kg/m^2/s") },
                { (0, 1, 69), ("Total column integrated cloud water", "kg/m^2") },
                { (0, 1, 70), ("Total column integrated cloud ice", "kg/m^2") },
                { (0, 1, 71), ("Hail mixing ratio", "kg/kg") },
                { (0, 1, 72), ("Total column integrated hail", "kg/m^2") },
                { (0, 1, 73), ("Hail precipitation rate", "kg/m^2/s") },
                { (0, 1, 74), ("Total column integrated graupel", "kg/m^2") },
                { (0, 1, 75), ("Graupel (snow pellets) precipitation rate", "kg/m^2/s") },
                { (0, 1, 76), ("Convective rain rate", "kg/m^2/s") },
                { (0, 1, 77), ("Large-scale rain rate", "kg/m^2/s") },
                { (0, 1, 78), ("Total column integrated water (all components)", "kg/m^2") },
                { (0, 1, 79), ("Evaporation rate", "kg/m^2/s") },
                { (0, 1, 80), ("Total condensate", "kg/kg") },
                { (0, 1, 81), ("Total column integrated condensate", "kg/m^2") },
                { (0, 1, 82), ("Cloud ice mixing ratio", "kg/kg") },
                { (0, 1, 83), ("Specific cloud liquid water content", "kg/kg") },
                { (0, 1, 84), ("Specific cloud ice water content", "kg/kg") },
                { (0, 1, 85), ("Specific rain water content", "kg/kg") },
                { (0, 1, 86), ("Specific snow water content", "kg/kg") },
                { (0, 1, 87), ("Stratiform precipitation rate", "kg/m^2/s") },
                { (0, 1, 88), ("Categorical convective precipitation", "code table") },
                { (0, 1, 90), ("Total kinematic moisture flux", "kg/kg m/s") },
                { (0, 1, 91), ("U-component kinematic moisture flux", "kg/kg m/s") },
                { (0, 1, 92), ("V-component kinematic moisture flux", "kg/kg m/s") },
                { (0, 1, 93), ("Relative humidity with respect to water", "%") },
                { (0, 1, 94), ("Relative humidity with respect to ice", "%") },
                { (0, 1, 95), ("Freezing or frozen precipitation rate", "kg/m^2/s") },
                { (0, 1, 96), ("Mass density of rain", "kg/m^3") },
                { (0, 1, 97), ("Mass density of snow", "kg/m^3") },
                { (0, 1, 98), ("Mass density of graupel", "kg/m^3") },
                { (0, 1, 99), ("Mass density of hail", "kg/m^3") },
                { (0, 1, 100), ("Specific number concentration of rain", "1/kg") },
                { (0, 1, 101), ("Specific number concentration of snow", "1/kg") },
                { (0, 1, 102), ("Specific number concentration of graupel", "1/kg") },
                { (0, 1, 103), ("Specific number concentration of hail", "1/kg") },
                { (0, 1, 104), ("Number density of rain", "1/m^3") },
                { (0, 1, 105), ("Number density of snow", "1/m^3") },
                { (0, 1, 106), ("Number density of graupel", "1/m^3") },
                { (0, 1, 107), ("Number density of hail", "1/m^3") },
                { (0, 1, 108), ("Specific humidity tendency due to parameterizations", "kg/kg/s") },
                { (0, 1, 121), ("Fraction of snow cover", "proportion") },
                { (0, 1, 122), ("Precipitation intensity index", "code table") },
                { (0, 1, 123), ("Dominant precipitation type", "code table") },
                { (0, 1, 124), ("Presence of showers", "code table") },
                { (0, 1, 125), ("Presence of blowing snow", "code table") },
                { (0, 1, 126), ("Presence of blizzard", "code table") },
                { (0, 1, 127), ("Ice pellets precipitation rate", "m/s") },
                { (0, 1, 128), ("Total solid precipitation rate", "kg/m^2/s") },
                { (0, 1, 192), ("Categorical rain", "code table") },
                { (0, 1, 193), ("Categorical freezing rain", "code table") },
                { (0, 1, 194), ("Categorical ice pellets", "code table") },
                { (0, 1, 195), ("Categorical snow", "code table") },
                { (0, 1, 196), ("Convective precipitation rate", "kg/m^2/s") },
                { (0, 1, 197), ("Horizontal moisture divergence", "kg/kg/s") },
                { (0, 1, 198), ("Minimum relative humidity", "%") },
                { (0, 1, 199), ("Potential evaporation", "kg/m^2") },
                { (0, 1, 200), ("Potential evaporation rate", "W/m^2") },
                { (0, 1, 201), ("Snow cover", "%") },
                { (0, 1, 202), ("Rain fraction of total liquid water", "numeric") },
                { (0, 1, 203), ("Rime factor", "numeric") },
                { (0, 1, 204), ("Total column integrated rain", "kg/m^2") },
                { (0, 1, 205), ("Total column integrated snow", "kg/m^2") },
                { (0, 1, 206), ("Total icing potential diagnostic", "numeric") },
                { (0, 1, 207), ("Number concentration for ice particles", "numeric") },
                { (0, 1, 208), ("Snow temperature", "K") },
                { (0, 1, 209), ("Total column integrated supercooled liquid water", "kg/m^2") },
                { (0, 1, 210), ("Total column integrated melting ice", "kg/m^2") },
                { (0, 1, 211), ("Evaporation - precipitation", "cm/day") },
                { (0, 1, 212), ("Sublimation (evaporation from snow)", "W/m^2") },
                { (0, 1, 213), ("Deep convective moistening rate", "kg/kg/s") },
                { (0, 1, 214), ("Shallow convective moistening rate", "kg/kg/s") },
                { (0, 1, 215), ("Vertical diffusion moistening rate", "kg/kg/s") },
                { (0, 1, 216), ("Condensation pressure of parcel lifted from surface", "Pa") },
                { (0, 1, 217), ("Large-scale moistening rate", "kg/kg/s") },
                { (0, 1, 218), ("Specific humidity at top of viscous sublayer", "kg/kg") },
                { (0, 1, 219), ("Maximum specific humidity at 2m", "kg/kg") },
                { (0, 1, 220), ("Minimum specific humidity at 2m", "kg/kg") },
                { (0, 1, 221), ("Liquid precipitation (rainfall)", "kg/m^2") },
                { (0, 1, 222), ("Snow temperature, depth average", "K") },
                { (0, 1, 223), ("Total precipitation (nearest grid point)", "kg/m^2") },
                { (0, 1, 224), ("Convective precipitation (nearest grid point)", "kg/m^2") },
                { (0, 1, 225), ("Freezing rain", "kg/m^2") },
                { (0, 1, 226), ("Predominant weather", "numeric") },
                { (0, 1, 227), ("Frozen rain", "kg/m^2") },
                { (0, 1, 228), ("Flat ice accumulation", "kg/m^2") },
                { (0, 1, 229), ("Line ice accumulation", "kg/m^2") },
                { (0, 1, 230), ("Sleet accumulation", "kg/m^2") },
                { (0, 1, 231), ("Precipitation potential index", "%") },
                { (0, 1, 232), ("Probability cloud ice present", "%") },
                { (0, 1, 233), ("Snow liquid ratio", "kg/kg") },
                { (0, 1, 234), ("Precipitation duration", "hour") },
                { (0, 1, 235), ("Cloud liquid mixing ratio", "kg/kg") },
                { (0, 1, 236), ("Hail accumulation", "m") },
                { (0, 1, 237), ("Total column integrated precipitation", "kg/m^2") },
                { (0, 1, 241), ("Total snow", "kg/m^2") },
                { (0, 1, 242), ("Relative humidity with respect to precipitable water", "%") },
                { (0, 1, 245), ("Hourly maximum of column vertical integrated graupel", "kg/m^2") },

                // Categoría 2: Momento (viento)
                { (0, 2, 0), ("Wind direction (from which blowing)", "deg") },
                { (0, 2, 1), ("Wind speed", "m/s") },
                { (0, 2, 2), ("U-component of wind", "m/s") },
                { (0, 2, 3), ("V-component of wind", "m/s") },
                { (0, 2, 4), ("Stream function", "m^2/s") },
                { (0, 2, 5), ("Velocity potential", "m^2/s") },
                { (0, 2, 6), ("Montgomery stream function", "m^2/s^2") },
                { (0, 2, 7), ("Sigma coordinate vertical velocity", "1/s") },
                { (0, 2, 8), ("Vertical velocity (pressure)", "Pa/s") },
                { (0, 2, 9), ("Vertical velocity (geometric)", "m/s") },
                { (0, 2, 10), ("Absolute vorticity", "1/s") },
                { (0, 2, 11), ("Absolute divergence", "1/s") },
                { (0, 2, 12), ("Relative vorticity", "1/s") },
                { (0, 2, 13), ("Relative divergence", "1/s") },
                { (0, 2, 14), ("Potential vorticity", "K m^2/kg/s") },
                { (0, 2, 15), ("Vertical U-component shear", "1/s") },
                { (0, 2, 16), ("Vertical V-component shear", "1/s") },
                { (0, 2, 17), ("Momentum flux, U-component", "N/m^2") },
                { (0, 2, 18), ("Momentum flux, V-component", "N/m^2") },
                { (0, 2, 19), ("Wind mixing energy", "J") },
                { (0, 2, 20), ("Boundary layer dissipation", "W/m^2") },
                { (0, 2, 21), ("Maximum wind speed", "m/s") },
                { (0, 2, 22), ("Wind speed (gust)", "m/s") },
                { (0, 2, 23), ("U-component of wind (gust)", "m/s") },
                { (0, 2, 24), ("V-component of wind (gust)", "m/s") },
                { (0, 2, 25), ("Vertical speed shear", "1/s") },
                { (0, 2, 26), ("Horizontal momentum flux", "N/m^2") },
                { (0, 2, 27), ("U-component storm motion", "m/s") },
                { (0, 2, 28), ("V-component storm motion", "m/s") },
                { (0, 2, 29), ("Drag coefficient", "numeric") },
                { (0, 2, 30), ("Frictional velocity", "m/s") },
                { (0, 2, 31), ("Turbulent diffusion coefficient for momentum", "m^2/s") },
                { (0, 2, 32), ("Eta coordinate vertical velocity", "1/s") },
                { (0, 2, 33), ("Wind fetch", "m") },
                { (0, 2, 34), ("Normal wind component", "m/s") },
                { (0, 2, 35), ("Tangential wind component", "m/s") },
                { (0, 2, 36), ("Amplitude function for Rossby wave envelope for meridional wind", "m/s") },
                { (0, 2, 37), ("Northward turbulent surface stress", "N/m^2 s") },
                { (0, 2, 38), ("Eastward turbulent surface stress", "N/m^2 s") },
                { (0, 2, 39), ("Eastward wind tendency due to parameterizations", "m/s^2") },
                { (0, 2, 40), ("Northward wind tendency due to parameterizations", "m/s^2") },
                { (0, 2, 41), ("U-component of geostrophic wind", "m/s") },
                { (0, 2, 42), ("V-component of geostrophic wind", "m/s") },
                { (0, 2, 43), ("Geostrophic wind direction", "deg") },
                { (0, 2, 44), ("Geostrophic wind speed", "m/s") },
                { (0, 2, 45), ("Unbalanced component of divergence", "1/s") },
                { (0, 2, 46), ("Vorticity advection", "1/s^2") },
                { (0, 2, 47), ("Surface roughness for heat", "m") },
                { (0, 2, 48), ("Surface roughness for moisture", "m") },
                { (0, 2, 49), ("Wind stress", "N/m^2") },
                { (0, 2, 50), ("Eastward wind stress", "N/m^2") },
                { (0, 2, 51), ("Northward wind stress", "N/m^2") },
                { (0, 2, 52), ("U-component of wind stress", "N/m^2") },
                { (0, 2, 53), ("V-component of wind stress", "N/m^2") },
                { (0, 2, 56), ("U-component of neutral wind", "m/s") },
                { (0, 2, 57), ("V-component of neutral wind", "m/s") },
                { (0, 2, 58), ("Magnitude of turbulent surface stress", "N/m^2") },
                { (0, 2, 59), ("Vertical divergence", "1/s") },
                { (0, 2, 68), ("Convective gust", "m/s") },
                { (0, 2, 69), ("Turbulent gust", "m/s") },
                { (0, 2, 70), ("Wind speed threshold for wind erosion", "m/s") },
                { (0, 2, 192), ("Vertical speed shear", "1/s") },
                { (0, 2, 193), ("Horizontal momentum flux", "N/m^2") },
                { (0, 2, 194), ("U-component storm motion", "m/s") },
                { (0, 2, 195), ("V-component storm motion", "m/s") },
                { (0, 2, 196), ("Drag coefficient", "numeric") },
                { (0, 2, 197), ("Frictional velocity", "m/s") },
                { (0, 2, 204), ("Vertical eddy diffusivity heat exchange", "m^2/s") },
                { (0, 2, 208), ("Vertical diffusion zonal acceleration", "m/s^2") },
                { (0, 2, 209), ("Vertical diffusion meridional acceleration", "m/s^2") },
                { (0, 2, 210), ("Gravity wave drag zonal acceleration", "m/s^2") },
                { (0, 2, 211), ("Gravity wave drag meridional acceleration", "m/s^2") },
                { (0, 2, 212), ("Convective zonal momentum mixing acceleration", "m/s^2") },
                { (0, 2, 213), ("Convective meridional momentum mixing acceleration", "m/s^2") },
                { (0, 2, 220), ("Hourly maximum of upward vertical velocity", "m/s") },
                { (0, 2, 221), ("Hourly maximum of downward vertical velocity", "m/s") },
                { (0, 2, 222), ("U component of hourly maximum 10m wind speed", "m/s") },
                { (0, 2, 223), ("V component of hourly maximum 10m wind speed", "m/s") },
                { (0, 2, 224), ("Ventilation rate", "m^2/s") },
                { (0, 2, 225), ("Transport wind speed", "m/s") },
                { (0, 2, 226), ("Transport wind direction", "deg") },
                { (0, 2, 231), ("Tropical wind direction", "deg") },
                { (0, 2, 232), ("Tropical wind speed", "m/s") },

                // Categoría 3: Masa (presión)
                { (0, 3, 0), ("Pressure", "Pa") },
                { (0, 3, 1), ("Pressure reduced to MSL", "Pa") },
                { (0, 3, 2), ("Pressure tendency", "Pa/s") },
                { (0, 3, 3), ("ICAO Standard Atmosphere reference height", "m") },
                { (0, 3, 4), ("Geopotential", "m^2/s^2") },
                { (0, 3, 5), ("Geopotential height", "gpm") },
                { (0, 3, 6), ("Geometric height", "m") },
                { (0, 3, 7), ("Standard deviation of height", "m") },
                { (0, 3, 8), ("Pressure anomaly", "Pa") },
                { (0, 3, 9), ("Geopotential height anomaly", "gpm") },
                { (0, 3, 10), ("Density", "kg/m^3") },
                { (0, 3, 11), ("Altimeter setting", "Pa") },
                { (0, 3, 12), ("Thickness", "m") },
                { (0, 3, 13), ("Pressure altitude", "m") },
                { (0, 3, 14), ("Density altitude", "m") },
                { (0, 3, 15), ("5-wave geopotential height", "gpm") },
                { (0, 3, 16), ("Zonal flux of gravity wave stress", "N/m^2") },
                { (0, 3, 17), ("Meridional flux of gravity wave stress", "N/m^2") },
                { (0, 3, 18), ("Planetary boundary layer height", "m") },
                { (0, 3, 19), ("5-wave geopotential height anomaly", "gpm") },
                { (0, 3, 20), ("Standard deviation of subgrid scale orography", "m") },
                { (0, 3, 21), ("Angle of subgrid scale orography", "rad") },
                { (0, 3, 22), ("Slope of subgrid scale orography", "numeric") },
                { (0, 3, 23), ("Gravity wave dissipation", "W/m^2") },
                { (0, 3, 24), ("Anisotropy of subgrid scale orography", "numeric") },
                { (0, 3, 25), ("Natural logarithm of pressure in Pa", "numeric") },
                { (0, 3, 26), ("Exner pressure", "numeric") },
                { (0, 3, 27), ("Updraught mass flux", "kg/m^2/s") },
                { (0, 3, 28), ("Downdraught mass flux", "kg/m^2/s") },
                { (0, 3, 29), ("Updraught detrainment rate", "kg/m^3/s") },
                { (0, 3, 30), ("Downdraught detrainment rate", "kg/m^3/s") },
                { (0, 3, 31), ("Unbalanced component of logarithm of surface pressure", "numeric") },
                { (0, 3, 32), ("Saturation water vapour pressure", "Pa") },
                { (0, 3, 33), ("Geometric altitude above mean sea level", "m") },
                { (0, 3, 34), ("Geometric height above ground level", "m") },
                { (0, 3, 44), ("Height of zero-degree wet-bulb temperature", "m") },
                { (0, 3, 45), ("Height of one-degree wet-bulb temperature", "m") },
                { (0, 3, 46), ("Pressure departure from hydrostatic state", "Pa") },
                { (0, 3, 192), ("MSLP (Eta model reduction)", "Pa") },
                { (0, 3, 193), ("5-wave geopotential height", "gpm") },
                { (0, 3, 194), ("Zonal flux of gravity wave stress", "N/m^2") },
                { (0, 3, 195), ("Meridional flux of gravity wave stress", "N/m^2") },
                { (0, 3, 196), ("Planetary boundary layer height", "m") },
                { (0, 3, 197), ("5-wave geopotential height anomaly", "gpm") },
                { (0, 3, 198), ("MSLP (MAPS system reduction)", "Pa") },
                { (0, 3, 199), ("3-hr pressure tendency (Std. Atmos. reduction)", "Pa/s") },
                { (0, 3, 200), ("Pressure of level from which parcel was lifted", "Pa") },
                { (0, 3, 201), ("X-gradient of log pressure", "1/m") },
                { (0, 3, 202), ("Y-gradient of log pressure", "1/m") },
                { (0, 3, 203), ("X-gradient of height", "1/m") },
                { (0, 3, 204), ("Y-gradient of height", "1/m") },
                { (0, 3, 205), ("Layer thickness", "m") },
                { (0, 3, 206), ("Natural log of surface pressure", "ln(kPa)") },
                { (0, 3, 207), ("Convective updraft mass flux", "kg/m^2/s") },
                { (0, 3, 208), ("Convective downdraft mass flux", "kg/m^2/s") },
                { (0, 3, 209), ("Convective detrainment mass flux", "kg/m^2/s") },
                { (0, 3, 211), ("Geopotential height (nearest grid point)", "gpm") },
                { (0, 3, 212), ("Pressure (nearest grid point)", "Pa") },
                { (0, 3, 222), ("Effective surface height", "m") },

                // Categoría 4: Radiación de onda corta
                { (0, 4, 0), ("Net short-wave radiation flux (surface)", "W/m^2") },
                { (0, 4, 1), ("Net short-wave radiation flux (top of atmosphere)", "W/m^2") },
                { (0, 4, 2), ("Short-wave radiation flux", "W/m^2") },
                { (0, 4, 3), ("Global radiation flux", "W/m^2") },
                { (0, 4, 4), ("Brightness temperature", "K") },
                { (0, 4, 5), ("Radiance (with respect to wavenumber)", "W/m/sr") },
                { (0, 4, 6), ("Radiance (with respect to wavelength)", "W/m^3/sr") },
                { (0, 4, 7), ("Downward short-wave radiation flux", "W/m^2") },
                { (0, 4, 8), ("Upward short-wave radiation flux", "W/m^2") },
                { (0, 4, 9), ("Net short-wave radiation flux", "W/m^2") },
                { (0, 4, 10), ("Photosynthetically active radiation", "W/m^2") },
                { (0, 4, 11), ("Net short-wave radiation flux, clear sky", "W/m^2") },
                { (0, 4, 12), ("Downward UV radiation", "W/m^2") },
                { (0, 4, 13), ("Direct short-wave radiation flux", "W/m^2") },
                { (0, 4, 14), ("Diffuse short-wave radiation flux", "W/m^2") },
                { (0, 4, 50), ("UV index (under clear sky)", "numeric") },
                { (0, 4, 51), ("UV index", "numeric") },
                { (0, 4, 52), ("Downward short-wave radiation flux, clear sky", "W/m^2") },
                { (0, 4, 53), ("Upward short-wave radiation flux, clear sky", "W/m^2") },
                { (0, 4, 54), ("Direct normal short-wave radiation flux", "W/m^2") },
                { (0, 4, 192), ("Downward short-wave radiation flux", "W/m^2") },
                { (0, 4, 193), ("Upward short-wave radiation flux", "W/m^2") },
                { (0, 4, 194), ("UV-B downward solar flux", "W/m^2") },
                { (0, 4, 195), ("Clear sky UV-B downward solar flux", "W/m^2") },
                { (0, 4, 196), ("Clear sky downward solar flux", "W/m^2") },
                { (0, 4, 197), ("Solar radiative heating rate", "K/s") },
                { (0, 4, 198), ("Clear sky upward solar flux", "W/m^2") },
                { (0, 4, 199), ("Cloud forcing net solar flux", "W/m^2") },
                { (0, 4, 200), ("Visible beam downward solar flux", "W/m^2") },
                { (0, 4, 201), ("Visible diffuse downward solar flux", "W/m^2") },
                { (0, 4, 202), ("Near IR beam downward solar flux", "W/m^2") },
                { (0, 4, 203), ("Near IR diffuse downward solar flux", "W/m^2") },
                { (0, 4, 204), ("Downward total radiation flux", "W/m^2") },
                { (0, 4, 205), ("Upward total radiation flux", "W/m^2") },

                // Categoría 5: Radiación de onda larga
                { (0, 5, 0), ("Net long-wave radiation flux (surface)", "W/m^2") },
                { (0, 5, 1), ("Net long-wave radiation flux (top of atmosphere)", "W/m^2") },
                { (0, 5, 2), ("Long-wave radiation flux", "W/m^2") },
                { (0, 5, 3), ("Downward long-wave radiation flux", "W/m^2") },
                { (0, 5, 4), ("Upward long-wave radiation flux", "W/m^2") },
                { (0, 5, 5), ("Net long-wave radiation flux", "W/m^2") },
                { (0, 5, 6), ("Net long-wave radiation flux, clear sky", "W/m^2") },
                { (0, 5, 7), ("Brightness temperature", "K") },
                { (0, 5, 8), ("Downward long-wave radiation flux, clear sky", "W/m^2") },
                { (0, 5, 192), ("Downward long-wave radiation flux", "W/m^2") },
                { (0, 5, 193), ("Upward long-wave radiation flux", "W/m^2") },
                { (0, 5, 194), ("Long-wave radiative heating rate", "K/s") },
                { (0, 5, 195), ("Clear sky upward long-wave flux", "W/m^2") },
                { (0, 5, 196), ("Clear sky downward long-wave flux", "W/m^2") },
                { (0, 5, 197), ("Cloud forcing net long-wave flux", "W/m^2") },

                // Categoría 6: Nubes
                { (0, 6, 0), ("Cloud ice", "kg/m^2") },
                { (0, 6, 1), ("Total cloud cover", "%") },
                { (0, 6, 2), ("Convective cloud cover", "%") },
                { (0, 6, 3), ("Low cloud cover", "%") },
                { (0, 6, 4), ("Medium cloud cover", "%") },
                { (0, 6, 5), ("High cloud cover", "%") },
                { (0, 6, 6), ("Cloud water", "kg/m^2") },
                { (0, 6, 7), ("Cloud amount", "%") },
                { (0, 6, 8), ("Cloud type", "code table") },
                { (0, 6, 9), ("Thunderstorm maximum tops", "m") },
                { (0, 6, 10), ("Thunderstorm coverage", "code table") },
                { (0, 6, 11), ("Cloud base", "m") },
                { (0, 6, 12), ("Cloud top", "m") },
                { (0, 6, 13), ("Ceiling", "m") },
                { (0, 6, 14), ("Non-convective cloud cover", "%") },
                { (0, 6, 15), ("Cloud work function", "J/kg") },
                { (0, 6, 16), ("Convective cloud efficiency", "proportion") },
                { (0, 6, 17), ("Total condensate", "kg/kg") },
                { (0, 6, 18), ("Total column integrated cloud water", "kg/m^2") },
                { (0, 6, 19), ("Total column integrated cloud ice", "kg/m^2") },
                { (0, 6, 20), ("Total column integrated condensate", "kg/m^2") },
                { (0, 6, 21), ("Ice fraction of total condensate", "proportion") },
                { (0, 6, 22), ("Cloud cover", "%") },
                { (0, 6, 23), ("Cloud ice mixing ratio", "kg/kg") },
                { (0, 6, 24), ("Sunshine", "numeric") },
                { (0, 6, 25), ("Horizontal extent of cumulonimbus (CB)", "%") },
                { (0, 6, 26), ("Height of convective cloud base", "m") },
                { (0, 6, 27), ("Height of convective cloud top", "m") },
                { (0, 6, 28), ("Number concentration of cloud droplets", "1/kg") },
                { (0, 6, 29), ("Number concentration of cloud ice", "1/kg") },
                { (0, 6, 30), ("Number density of cloud droplets", "1/m^3") },
                { (0, 6, 31), ("Number density of cloud ice", "1/m^3") },
                { (0, 6, 32), ("Fraction of cloud cover", "numeric") },
                { (0, 6, 33), ("Sunshine duration", "s") },
                { (0, 6, 50), ("Fog", "%") },
                { (0, 6, 192), ("Non-convective cloud cover", "%") },
                { (0, 6, 193), ("Cloud work function", "J/kg") },
                { (0, 6, 194), ("Convective cloud efficiency", "numeric") },
                { (0, 6, 195), ("Total condensate", "kg/kg") },
                { (0, 6, 196), ("Total column integrated cloud water", "kg/m^2") },
                { (0, 6, 197), ("Total column integrated cloud ice", "kg/m^2") },
                { (0, 6, 198), ("Total column integrated condensate", "kg/m^2") },
                { (0, 6, 199), ("Ice fraction of total condensate", "numeric") },
                { (0, 6, 200), ("Convective cloud mass flux", "Pa/s") },
                { (0, 6, 201), ("Sunshine duration", "s") },

                // Categoría 7: Estabilidad termodinámica
                { (0, 7, 0), ("Parcel lifted index (to 500 hPa)", "K") },
                { (0, 7, 1), ("Best lifted index (to 500 hPa)", "K") },
                { (0, 7, 2), ("K index", "K") },
                { (0, 7, 3), ("KO index", "K") },
                { (0, 7, 4), ("Total totals index", "K") },
                { (0, 7, 5), ("Sweat index", "numeric") },
                { (0, 7, 6), ("Convective available potential energy", "J/kg") },
                { (0, 7, 7), ("Convective inhibition", "J/kg") },
                { (0, 7, 8), ("Storm relative helicity", "J/kg") },
                { (0, 7, 9), ("Energy helicity index", "numeric") },
                { (0, 7, 10), ("Surface lifted index", "K") },
                { (0, 7, 11), ("Best (4 layer) lifted index", "K") },
                { (0, 7, 12), ("Richardson number", "numeric") },
                { (0, 7, 13), ("Showalter index", "K") },
                { (0, 7, 15), ("Updraft helicity", "m^2/s^2") },
                { (0, 7, 16), ("Bulk Richardson number", "numeric") },
                { (0, 7, 17), ("Gradient Richardson number", "numeric") },
                { (0, 7, 18), ("Flux Richardson number", "numeric") },
                { (0, 7, 19), ("Convective available potential energy - shear", "m^2/s^2") },
                { (0, 7, 192), ("Surface lifted index", "K") },
                { (0, 7, 193), ("Best (4 layer) lifted index", "K") },
                { (0, 7, 194), ("Richardson number", "numeric") },
                { (0, 7, 195), ("Convective weather detection index", "numeric") },
                { (0, 7, 196), ("Ultra violet index", "W/m^2") },
                { (0, 7, 197), ("Updraft helicity", "m^2/s^2") },
                { (0, 7, 198), ("Leaf area index", "numeric") },
                { (0, 7, 199), ("Hourly maximum of updraft helicity", "m^2/s^2") },
                { (0, 7, 200), ("Hourly minimum of updraft helicity", "m^2/s^2") },
                { (0, 7, 201), ("Bourgouin negative energy layer (surface to freezing level)", "J/kg") },
                { (0, 7, 202), ("Bourgouin positive energy layer (2k ft AGL to 400 hPa)", "J/kg") },
                { (0, 7, 203), ("Downdraft CAPE", "J/kg") },
                { (0, 7, 204), ("Effective storm relative helicity", "m^2/s^2") },

                // Categoría 16: Imágenes de radar de pronóstico
                { (0, 16, 0), ("Equivalent radar reflectivity factor for rain", "mm^6/m^3") },
                { (0, 16, 1), ("Equivalent radar reflectivity factor for snow", "mm^6/m^3") },
                { (0, 16, 2), ("Equivalent radar reflectivity factor for parameterized convection", "mm^6/m^3") },
                { (0, 16, 3), ("Echo top", "m") },
                { (0, 16, 4), ("Reflectivity", "dB") },
                { (0, 16, 5), ("Composite reflectivity", "dB") },
                { (0, 16, 6), ("Precipitation rate", "kg/m^2/s") },
                { (0, 16, 7), ("Layer maximum precipitation rate", "kg/m^2/s") },
                { (0, 16, 8), ("Layer maximum reflectivity", "dB") },
                { (0, 16, 192), ("Equivalent radar reflectivity factor for rain", "mm^6/m^3") },
                { (0, 16, 193), ("Equivalent radar reflectivity factor for snow", "mm^6/m^3") },
                { (0, 16, 194), ("Equivalent radar reflectivity factor for parameterized convection", "mm^6/m^3") },
                { (0, 16, 195), ("Reflectivity", "dB") },
                { (0, 16, 196), ("Composite reflectivity", "dB") },
                { (0, 16, 197), ("Echo top", "m") },
                { (0, 16, 198), ("Hourly maximum of simulated reflectivity", "dB") },
                { (0, 16, 199), ("Hourly maximum of composite reflectivity", "dB") },

                // Categoría 19: Propiedades físicas atmosféricas
                { (0, 19, 0), ("Visibility", "m") },
                { (0, 19, 1), ("Albedo", "%") },
                { (0, 19, 2), ("Thunderstorm probability", "%") },
                { (0, 19, 3), ("Mixed layer depth", "m") },
                { (0, 19, 4), ("Volcanic ash", "code table") },
                { (0, 19, 5), ("Icing top", "m") },
                { (0, 19, 6), ("Icing base", "m") },
                { (0, 19, 7), ("Icing", "code table") },
                { (0, 19, 8), ("Turbulence top", "m") },
                { (0, 19, 9), ("Turbulence base", "m") },
                { (0, 19, 10), ("Turbulence", "code table") },
                { (0, 19, 11), ("Turbulent kinetic energy", "J/kg") },
                { (0, 19, 12), ("Planetary boundary layer regime", "code table") },
                { (0, 19, 13), ("Contrail intensity", "code table") },
                { (0, 19, 14), ("Contrail engine type", "code table") },
                { (0, 19, 15), ("Contrail top", "m") },
                { (0, 19, 16), ("Contrail base", "m") },
                { (0, 19, 17), ("Maximum snow albedo", "%") },
                { (0, 19, 18), ("Snow-free albedo", "%") },
                { (0, 19, 19), ("Snow albedo", "%") },
                { (0, 19, 20), ("Icing", "%") },
                { (0, 19, 21), ("In-cloud turbulence", "%") },
                { (0, 19, 22), ("Clear air turbulence (CAT)", "%") },
                { (0, 19, 23), ("Supercooled large droplet probability", "%") },
                { (0, 19, 24), ("Convective turbulent kinetic energy", "J/kg") },
                { (0, 19, 25), ("Weather", "code table") },
                { (0, 19, 26), ("Convective outlook", "code table") },
                { (0, 19, 30), ("Eddy dissipation parameter", "m^2/3/s") },
                { (0, 19, 32), ("Highest freezing level", "m") },
                { (0, 19, 40), ("Snow level", "m") },
                { (0, 19, 192), ("Maximum snow albedo", "%") },
                { (0, 19, 193), ("Snow-free albedo", "%") },
                { (0, 19, 197), ("Tornado probability", "%") },
                { (0, 19, 198), ("Hail probability", "%") },
                { (0, 19, 199), ("Wind probability", "%") },
                { (0, 19, 200), ("Significant tornado probability", "%") },
                { (0, 19, 201), ("Significant hail probability", "%") },
                { (0, 19, 202), ("Significant wind probability", "%") },
                { (0, 19, 203), ("Categorical thunderstorm", "code table") },
                { (0, 19, 204), ("Number of mixed layers next to surface", "numeric") },
                { (0, 19, 205), ("Flight category", "numeric") },
                { (0, 19, 217), ("Supercooled large droplet (SLD) icing", "code table") },
                { (0, 19, 233), ("Icing probability", "numeric") },
                { (0, 19, 234), ("Icing severity", "numeric") },
                { (0, 19, 235), ("Joint fire weather probability", "%") },
                { (0, 19, 236), ("Snow level", "m") },
                { (0, 19, 237), ("Dry thunderstorm probability", "%") },

                // === Disciplina 1 - Hidrología ===
                // Categoría 0: Productos básicos de hidrología
                { (1, 0, 0), ("Flash flood guidance", "kg/m^2") },
                { (1, 0, 1), ("Flash flood runoff", "kg/m^2") },
                { (1, 0, 2), ("Remotely sensed snow cover", "code table") },
                { (1, 0, 3), ("Elevation of snow-covered terrain", "code table") },
                { (1, 0, 4), ("Snow water equivalent percent of normal", "%") },
                { (1, 0, 5), ("Baseflow-groundwater runoff", "kg/m^2") },
                { (1, 0, 6), ("Storm surface runoff", "kg/m^2") },
                { (1, 0, 7), ("Discharge from rivers or streams", "m^3/s") },
                { (1, 0, 8), ("Group water upper storage", "kg/m^2") },
                { (1, 0, 9), ("Group water lower storage", "kg/m^2") },
                { (1, 0, 10), ("Side flow into river channel", "m^3/s/m") },
                { (1, 0, 11), ("River storage of water", "m^3") },
                { (1, 0, 12), ("Flood plain storage of water", "m^3") },
                { (1, 0, 13), ("Depth of water on soil surface", "kg/m^2") },
                { (1, 0, 14), ("Upstream accumulated precipitation", "kg/m^2") },
                { (1, 0, 15), ("Upstream accumulated snow melt", "kg/m^2") },
                { (1, 0, 16), ("Percolation rate", "kg/m^2/s") },
                { (1, 0, 192), ("Baseflow-groundwater runoff", "kg/m^2") },
                { (1, 0, 193), ("Storm surface runoff", "kg/m^2") },

                // === Disciplina 2 - Superficie terrestre ===
                // Categoría 0: Vegetación/biomasa
                { (2, 0, 0), ("Land cover (0=sea, 1=land)", "proportion") },
                { (2, 0, 1), ("Surface roughness", "m") },
                { (2, 0, 2), ("Soil temperature", "K") },
                { (2, 0, 3), ("Soil moisture content", "kg/m^2") },
                { (2, 0, 4), ("Vegetation", "%") },
                { (2, 0, 5), ("Water runoff", "kg/m^2") },
                { (2, 0, 6), ("Evapotranspiration", "kg/m^2/s") },
                { (2, 0, 7), ("Model terrain height", "m") },
                { (2, 0, 8), ("Land use", "code table") },
                { (2, 0, 9), ("Volumetric soil moisture content", "proportion") },
                { (2, 0, 10), ("Ground heat flux", "W/m^2") },
                { (2, 0, 11), ("Moisture availability", "%") },
                { (2, 0, 12), ("Exchange coefficient", "kg/m^2/s") },
                { (2, 0, 13), ("Plant canopy surface water", "kg/m^2") },
                { (2, 0, 14), ("Blackadar's mixing length scale", "m") },
                { (2, 0, 15), ("Canopy conductance", "m/s") },
                { (2, 0, 16), ("Minimal stomatal resistance", "s/m") },
                { (2, 0, 17), ("Wilting point", "proportion") },
                { (2, 0, 22), ("Soil moisture", "kg/m^3") },
                { (2, 0, 23), ("Column-integrated soil water", "kg/m^2") },
                { (2, 0, 24), ("Heat flux", "W/m^2") },
                { (2, 0, 25), ("Volumetric soil moisture", "m^3/m^3") },
                { (2, 0, 26), ("Wilting point", "kg/m^3") },
                { (2, 0, 27), ("Volumetric wilting point", "m^3/m^3") },
                { (2, 0, 28), ("Leaf area index", "numeric") },
                { (2, 0, 29), ("Evergreen forest cover", "proportion") },
                { (2, 0, 30), ("Deciduous forest cover", "proportion") },
                { (2, 0, 31), ("Normalized differential vegetation index (NDVI)", "numeric") },
                { (2, 0, 32), ("Root depth of vegetation", "m") },
                { (2, 0, 33), ("Water runoff and drainage", "kg/m^2") },
                { (2, 0, 34), ("Surface water runoff", "kg/m^2") },
                { (2, 0, 35), ("Tile class", "code table") },
                { (2, 0, 36), ("Tile fraction", "proportion") },
                { (2, 0, 37), ("Tile percentage", "%") },
                { (2, 0, 38), ("Soil volumetric ice content (water equivalent)", "m^3/m^3") },
                { (2, 0, 39), ("Evapotranspiration rate", "kg/m^2/s") },
                { (2, 0, 40), ("Potential evapotranspiration rate", "kg/m^2/s") },
                { (2, 0, 41), ("Snow melt rate", "kg/m^2/s") },
                { (2, 0, 42), ("Water runoff and drainage rate", "kg/m^2/s") },
                { (2, 0, 62), ("Emissivity", "proportion") },
                { (2, 0, 63), ("Canopy air temperature", "K") },
                { (2, 0, 192), ("Volumetric soil moisture content", "fraction") },
                { (2, 0, 193), ("Ground heat flux", "W/m^2") },
                { (2, 0, 194), ("Moisture availability", "%") },
                { (2, 0, 195), ("Exchange coefficient", "kg/m^3 m/s") },
                { (2, 0, 196), ("Plant canopy surface water", "kg/m^2") },
                { (2, 0, 197), ("Blackadar's mixing length scale", "m") },
                { (2, 0, 198), ("Vegetation type", "numeric") },
                { (2, 0, 199), ("Canopy conductance", "m/s") },
                { (2, 0, 200), ("Minimal stomatal resistance", "s/m") },
                { (2, 0, 201), ("Wilting point", "fraction") },
                { (2, 0, 207), ("Ice-free water surface", "%") },
                { (2, 0, 210), ("Vegetation canopy temperature", "K") },
                { (2, 0, 211), ("Surface water storage", "kg/m^2") },
                { (2, 0, 212), ("Liquid soil moisture content (non-frozen)", "kg/m^2") },
                { (2, 0, 217), ("Normalized difference vegetation index", "numeric") },
                { (2, 0, 229), ("Canopy water evaporation", "W/m^2") },
                { (2, 0, 230), ("Transpiration", "W/m^2") },
                { (2, 0, 231), ("Seasonally minimum green vegetation fraction", "%") },
                { (2, 0, 232), ("Seasonally maximum green vegetation fraction", "%") },
                { (2, 0, 233), ("Land fraction", "fraction") },
                { (2, 0, 234), ("Lake fraction", "fraction") },

                // Categoría 3: Productos de suelo
                { (2, 3, 0), ("Soil type", "code table") },
                { (2, 3, 1), ("Upper layer soil temperature", "K") },
                { (2, 3, 2), ("Upper layer soil moisture", "kg/m^3") },
                { (2, 3, 3), ("Lower layer soil moisture", "kg/m^3") },
                { (2, 3, 4), ("Bottom layer soil temperature", "K") },
                { (2, 3, 5), ("Liquid volumetric soil moisture (non-frozen)", "proportion") },
                { (2, 3, 6), ("Number of soil layers in root zone", "numeric") },
                { (2, 3, 7), ("Transpiration stress-onset (soil moisture)", "proportion") },
                { (2, 3, 8), ("Direct evaporation cease (soil moisture)", "proportion") },
                { (2, 3, 9), ("Soil porosity", "proportion") },
                { (2, 3, 10), ("Liquid volumetric soil moisture (non-frozen)", "m^3/m^3") },
                { (2, 3, 18), ("Soil temperature", "K") },
                { (2, 3, 19), ("Soil moisture", "kg/m^3") },
                { (2, 3, 20), ("Column-integrated soil moisture", "kg/m^2") },
                { (2, 3, 21), ("Soil ice", "kg/m^3") },
                { (2, 3, 22), ("Column-integrated soil ice", "kg/m^2") },
                { (2, 3, 23), ("Liquid water in snow pack", "kg/m^2") },
                { (2, 3, 24), ("Frost index", "kg/day") },
                { (2, 3, 25), ("Snow depth at elevation bands", "kg/m^2") },
                { (2, 3, 26), ("Soil heat flux", "W/m^2") },
                { (2, 3, 27), ("Soil depth", "m") },
                { (2, 3, 28), ("Snow temperature", "K") },
                { (2, 3, 29), ("Ice temperature", "K") },
                { (2, 3, 192), ("Liquid volumetric soil moisture (non-frozen)", "proportion") },
                { (2, 3, 193), ("Number of soil layers in root zone", "numeric") },
                { (2, 3, 194), ("Surface slope type", "numeric") },
                { (2, 3, 195), ("Transpiration stress-onset (soil moisture)", "proportion") },
                { (2, 3, 196), ("Direct evaporation cease (soil moisture)", "proportion") },
                { (2, 3, 197), ("Soil porosity", "proportion") },
                { (2, 3, 198), ("Direct evaporation from bare soil", "W/m^2") },
                { (2, 3, 199), ("Land surface precipitation accumulation", "kg/m^2") },
                { (2, 3, 200), ("Bare soil surface skin temperature", "K") },
                { (2, 3, 201), ("Average surface skin temperature", "K") },
                { (2, 3, 202), ("Effective radiative skin temperature", "K") },
                { (2, 3, 203), ("Field capacity", "fraction") },
                { (2, 3, 204), ("Soil moisture availability in the top soil layer", "%") },

                // Categoría 4: Meteorología de incendios
                { (2, 4, 0), ("Fire outlook", "code table") },
                { (2, 4, 1), ("Fire outlook due to dry thunderstorm", "code table") },
                { (2, 4, 2), ("Haines index", "numeric") },
                { (2, 4, 3), ("Fire burned area", "%") },
                { (2, 4, 4), ("Fosberg index", "numeric") },
                { (2, 4, 5), ("Forest fire weather index", "numeric") },
                { (2, 4, 6), ("Fine fuel moisture code", "numeric") },
                { (2, 4, 7), ("Duff moisture code", "numeric") },
                { (2, 4, 8), ("Drought code", "numeric") },
                { (2, 4, 9), ("Initial fire spread index", "numeric") },
                { (2, 4, 10), ("Fire buildup index", "numeric") },
                { (2, 4, 11), ("Fire daily severity rating", "numeric") },
                { (2, 4, 12), ("Keetch-Byram drought index", "numeric") },
                { (2, 4, 13), ("Drought factor", "numeric") },
                { (2, 4, 14), ("Rate of spread", "m/s") },
                { (2, 4, 15), ("Fire danger index", "numeric") },
                { (2, 4, 16), ("Spread component", "numeric") },
                { (2, 4, 17), ("Burning index", "numeric") },
                { (2, 4, 18), ("Ignition component", "%") },
                { (2, 4, 19), ("Energy release component", "J/m^2") },
                { (2, 4, 26), ("Wildfire potential", "numeric") },
                { (2, 4, 36), ("Fire radiative power", "W") },

                // Categoría 5: Glaciares y hielo continental
                { (2, 5, 0), ("Glacier cover", "proportion") },
                { (2, 5, 1), ("Glacier temperature", "K") },

                // === Disciplina 10 - Oceanografía ===
                // Categoría 0: Olas
                { (10, 0, 3), ("Significant height of combined wind waves and swell", "m") },
                { (10, 0, 4), ("Direction of wind waves", "deg") },
                { (10, 0, 5), ("Significant height of wind waves", "m") },
                { (10, 0, 6), ("Mean period of wind waves", "s") },
                { (10, 0, 7), ("Direction of swell waves", "deg") },
                { (10, 0, 8), ("Significant height of swell waves", "m") },
                { (10, 0, 9), ("Mean period of swell waves", "s") },
                { (10, 0, 10), ("Primary wave direction", "deg") },
                { (10, 0, 11), ("Primary wave mean period", "s") },
                { (10, 0, 12), ("Secondary wave direction", "deg") },
                { (10, 0, 13), ("Secondary wave mean period", "s") },
                { (10, 0, 14), ("Direction of combined wind waves and swell", "deg") },
                { (10, 0, 15), ("Mean period of combined wind waves and swell", "s") },
                { (10, 0, 16), ("Coefficient of drag with waves", "numeric") },
                { (10, 0, 17), ("Friction velocity", "m/s") },
                { (10, 0, 18), ("Wave stress", "N/m^2") },
                { (10, 0, 19), ("Normalised wave stress", "numeric") },
                { (10, 0, 20), ("Mean square slope of waves", "numeric") },
                { (10, 0, 21), ("U-component surface Stokes drift", "m/s") },
                { (10, 0, 22), ("V-component surface Stokes drift", "m/s") },
                { (10, 0, 23), ("Period of maximum individual wave height", "s") },
                { (10, 0, 24), ("Maximum individual wave height", "m") },
                { (10, 0, 25), ("Inverse mean wave frequency", "s") },
                { (10, 0, 28), ("Mean zero-crossing wave period", "s") },
                { (10, 0, 31), ("Wave directional width", "numeric") },
                { (10, 0, 34), ("Peak wave period", "s") },
                { (10, 0, 35), ("Peak period of the wind waves", "s") },
                { (10, 0, 36), ("Peak period of the total swell", "s") },
                { (10, 0, 45), ("Spectral peakedness factor", "1/s") },
                { (10, 0, 46), ("Peak wave direction", "deg") },
                { (10, 0, 192), ("Wave steepness", "proportion") },
                { (10, 0, 193), ("Wave length", "numeric") },

                // Categoría 1: Corrientes
                { (10, 1, 0), ("Current direction", "deg") },
                { (10, 1, 1), ("Current speed", "m/s") },
                { (10, 1, 2), ("U-component of current", "m/s") },
                { (10, 1, 3), ("V-component of current", "m/s") },
                { (10, 1, 4), ("Rip current occurrence probability", "%") },
                { (10, 1, 5), ("Eastward current", "m/s") },
                { (10, 1, 6), ("Northward current", "m/s") },
                { (10, 1, 192), ("Ocean mixed layer U velocity", "m/s") },
                { (10, 1, 193), ("Ocean mixed layer V velocity", "m/s") },
                { (10, 1, 194), ("Barotropic U velocity", "m/s") },
                { (10, 1, 195), ("Barotropic V velocity", "m/s") },

                // Categoría 2: Hielo
                { (10, 2, 0), ("Ice cover", "proportion") },
                { (10, 2, 1), ("Ice thickness", "m") },
                { (10, 2, 2), ("Direction of ice drift", "deg") },
                { (10, 2, 3), ("Speed of ice drift", "m/s") },
                { (10, 2, 4), ("U-component of ice drift", "m/s") },
                { (10, 2, 5), ("V-component of ice drift", "m/s") },
                { (10, 2, 6), ("Ice growth rate", "m/s") },
                { (10, 2, 7), ("Ice divergence", "1/s") },
                { (10, 2, 8), ("Ice temperature", "K") },
                { (10, 2, 9), ("Module of ice internal pressure", "Pa m") },
                { (10, 2, 13), ("Snow temperature (over sea ice)", "K") },
                { (10, 2, 14), ("Albedo", "numeric") },
                { (10, 2, 15), ("Sea ice volume per unit area", "m^3/m^2") },
                { (10, 2, 16), ("Snow volume over sea ice per unit area", "m^3/m^2") },
                { (10, 2, 17), ("Sea ice heat content", "J/m^2") },
                { (10, 2, 27), ("Freezing/melting potential", "W/m^2") },
                { (10, 2, 31), ("Downward short-wave radiation flux", "W/m^2") },

                // Categoría 3: Propiedades de superficie
                { (10, 3, 0), ("Water temperature", "K") },
                { (10, 3, 1), ("Deviation of sea level from mean", "m") },
                { (10, 3, 2), ("Heat exchange coefficient", "numeric") },
                { (10, 3, 3), ("Practical salinity", "numeric") },
                { (10, 3, 4), ("Downward heat flux", "W/m^2") },
                { (10, 3, 5), ("Eastward surface stress", "N/m^2") },
                { (10, 3, 6), ("Northward surface stress", "N/m^2") },
                { (10, 3, 7), ("X-component surface stress", "N/m^2") },
                { (10, 3, 8), ("Y-component surface stress", "N/m^2") },
                { (10, 3, 11), ("Steric change in sea surface height", "m") },
                { (10, 3, 12), ("Sea salt flux", "kg/m^2/s") },
                { (10, 3, 13), ("Net upward water flux", "kg/m^2/s") },
                { (10, 3, 14), ("Eastward surface water velocity", "m/s") },
                { (10, 3, 15), ("Northward surface water velocity", "m/s") },
                { (10, 3, 21), ("Salinity", "kg/kg") },
                { (10, 3, 22), ("Downward short-wave radiation flux", "W/m^2") },
                { (10, 3, 192), ("Hurricane storm surge", "m") },
                { (10, 3, 193), ("Extra tropical storm surge", "m") },
                { (10, 3, 194), ("Ocean surface elevation relative to geoid", "m") },
                { (10, 3, 195), ("Sea surface height relative to geoid", "m") },
                { (10, 3, 196), ("Ocean mixed layer potential density (reference 2000m)", "kg/m^3") },
                { (10, 3, 197), ("Net air-ocean heat flux", "W/m^2") },
                { (10, 3, 198), ("Assimilative heat flux", "W/m^2") },
                { (10, 3, 205), ("Total water level accounting for tide, wind and waves", "m") },
                { (10, 3, 242), ("20% tropical cyclone storm surge exceedance", "m") },
                { (10, 3, 245), ("50% tropical cyclone storm surge exceedance", "m") },
                { (10, 3, 250), ("Extra tropical storm surge combined surge and tide", "m") },
                { (10, 3, 251), ("Tide", "m") },

                // Categoría 4: Propiedades subsuperficiales
                { (10, 4, 0), ("Main thermocline depth", "m") },
                { (10, 4, 1), ("Main thermocline anomaly", "m") },
                { (10, 4, 2), ("Transient thermocline depth", "m") },
                { (10, 4, 3), ("Salinity", "kg/kg") },
                { (10, 4, 4), ("Ocean vertical heat diffusivity", "m^2/s") },
                { (10, 4, 5), ("Ocean vertical salt diffusivity", "m^2/s") },
                { (10, 4, 6), ("Ocean vertical momentum diffusivity", "m^2/s") },
                { (10, 4, 7), ("Bathymetry", "m") },
                { (10, 4, 14), ("Water depth", "m") },
                { (10, 4, 15), ("Water temperature", "K") },
                { (10, 4, 16), ("Water density", "kg/m^3") },
                { (10, 4, 18), ("Water potential temperature", "K") },
                { (10, 4, 19), ("Water potential density", "kg/m^3") },
                { (10, 4, 21), ("Practical salinity", "psu") },
                { (10, 4, 22), ("Water column-integrated heat content", "J/m^2") },
                { (10, 4, 23), ("Eastward water velocity", "m/s") },
                { (10, 4, 24), ("Northward water velocity", "m/s") },
                { (10, 4, 25), ("X-component water velocity", "m/s") },
                { (10, 4, 26), ("Y-component water velocity", "m/s") },
                { (10, 4, 27), ("Upward water velocity", "m/s") },
                { (10, 4, 28), ("Vertical eddy diffusivity", "m^2/s") },
                { (10, 4, 52), ("Mixed layer depth", "m") },
                { (10, 4, 192), ("3-D temperature", "C") },
                { (10, 4, 193), ("3-D salinity", "psu") },
                { (10, 4, 194), ("Barotropic kinetic energy", "J/kg") },
                { (10, 4, 195), ("Geometric depth below sea surface", "m") },
                { (10, 4, 196), ("Interface depths", "m") },
                { (10, 4, 197), ("Ocean heat content", "J/m^2") },
            };

        // Tabla 0.0 - Disciplina de los datos procesados.
        private static readonly Dictionary<int, string> Disciplines = new Dictionary<int, string>
        {
            { 0, "Meteorological Products" },
            { 1, "Hydrological Products" },
            { 2, "Land Surface Products" },
            { 3, "Satellite Remote Sensing Products" },
            { 4, "Space Weather Products" },
            { 10, "Oceanographic Products" },
            { 20, "Health and Socioeconomic Impacts" },
            { 191, "Computational Parameters" },
        };

        // Tabla 4.1 - Categoría de parámetro por disciplina. Clave (disciplina, categoría).
        private static readonly Dictionary<(int, int), string> Categories =
            new Dictionary<(int, int), string>
            {
                // Disciplina 0 - Meteorología
                { (0, 0), "Temperature" },
                { (0, 1), "Moisture" },
                { (0, 2), "Momentum" },
                { (0, 3), "Mass" },
                { (0, 4), "Short-wave Radiation" },
                { (0, 5), "Long-wave Radiation" },
                { (0, 6), "Cloud" },
                { (0, 7), "Thermodynamic Stability Indices" },
                { (0, 8), "Kinematic Stability Indices" },
                { (0, 9), "Temperature Probabilities" },
                { (0, 10), "Moisture Probabilities" },
                { (0, 11), "Momentum Probabilities" },
                { (0, 12), "Mass Probabilities" },
                { (0, 13), "Aerosols" },
                { (0, 14), "Trace Gases" },
                { (0, 15), "Radar" },
                { (0, 16), "Forecast Radar Imagery" },
                { (0, 17), "Electrodynamics" },
                { (0, 18), "Nuclear/Radiology" },
                { (0, 19), "Physical Atmospheric Properties" },
                { (0, 20), "Atmospheric Chemical Constituents" },
                { (0, 21), "Thermodynamic Properties" },
                { (0, 22), "Drought Indices" },
                { (0, 190), "CCITT IA5 String" },
                { (0, 191), "Miscellaneous" },
                { (0, 192), "Covariance" },
                // Disciplina 1 - Hidrología
                { (1, 0), "Hydrology Basic Products" },
                { (1, 1), "Hydrology Probabilities" },
                { (1, 2), "Inland Water and Sediment Properties" },
                // Disciplina 2 - Superficie terrestre
                { (2, 0), "Vegetation/Biomass" },
                { (2, 1), "Agricultural/Aquacultural Special Products" },
                { (2, 3), "Soil Products" },
                { (2, 4), "Fire Weather Products" },
                { (2, 5), "Glaciers and Inland Ice Products" },
                { (2, 6), "Urban Areas" },
                { (2, 7), "Thermodynamic Properties" },
                // Disciplina 3 - Teledetección por satélite
                { (3, 0), "Image Format Products" },
                { (3, 1), "Quantitative Products" },
                { (3, 2), "Cloud Properties" },
                { (3, 3), "Flight Rules Conditions" },
                { (3, 4), "Volcanic Ash" },
                { (3, 5), "Sea Surface Temperature" },
                { (3, 6), "Solar Radiation" },
                { (3, 192), "Forecast Satellite Imagery" },
                // Disciplina 4 - Meteorología espacial
                { (4, 0), "Temperature" },
                { (4, 1), "Momentum" },
                { (4, 2), "Charged Particle Mass and Number" },
                { (4, 3), "Electric and Magnetic Fields" },
                { (4, 4), "Energetic Particles" },
                { (4, 5), "Waves" },
                { (4, 6), "Solar Electromagnetic Emissions" },
                { (4, 7), "Terrestrial Electromagnetic Emissions" },
                { (4, 8), "Imagery" },
                { (4, 9), "Ion-Neutral Coupling" },
                { (4, 10), "Space Weather Indices" },
                // Disciplina 10 - Oceanografía
                { (10, 0), "Waves" },
                { (10, 1), "Currents" },
                { (10, 2), "Ice" },
                { (10, 3), "Surface Properties" },
                { (10, 4), "Subsurface Properties" },
                { (10, 191), "Miscellaneous" },
                // Disciplina 20 - Salud e impacto socioeconómico
                { (20, 0), "Health Indicators" },
                { (20, 1), "Epidemiology" },
                { (20, 2), "Socioeconomic Indicators" },
                { (20, 3), "Renewable Energy Sector" },
                { (20, 4), "Meteorological and Hydrological Hazard Indices" },
                { (20, 5), "Environmental Hazard Indices" },
                // Disciplina 191 - Parámetros computacionales
                { (191, 0), "Stochastic Parameterizations" },
            };

        // Tabla 4.0 - Número de plantilla de definición de producto (subconjunto común).
        private static readonly Dictionary<int, string> ProductTemplates = new Dictionary<int, string>
        {
            { 0, "Analysis or forecast at a horizontal level/layer at a point in time" },
            { 1, "Individual ensemble forecast at a horizontal level/layer at a point in time" },
            { 2, "Derived forecast based on all ensemble members at a horizontal level/layer at a point in time" },
            { 3, "Derived forecast based on ensemble cluster over rectangular area" },
            { 4, "Derived forecast based on ensemble cluster over circular area" },
            { 5, "Probability forecast at a horizontal level/layer at a point in time" },
            { 6, "Percentile forecast at a horizontal level/layer at a point in time" },
            { 7, "Analysis or forecast error at a horizontal level/layer at a point in time" },
            { 8, "Statistical value at a horizontal level/layer in a time interval" },
            { 9, "Probability forecast over a time interval" },
            { 10, "Percentile forecast over a time interval" },
            { 11, "Individual ensemble forecast over a time interval" },
            { 12, "Derived ensemble forecast over a time interval" },
            { 15, "Statistical value over a spatial area at a point in time" },
            { 20, "Radar product" },
            { 30, "Satellite product (deprecated)" },
            { 31, "Satellite product" },
            { 51, "Categorical forecast at a horizontal level/layer at a point in time" },
            { 254, "CCITT IA5 character string" },
        };

        private static readonly Dictionary<int, string> Levels = new Dictionary<int, string>
        {
            { 1, "Ground or water surface" },
            { 2, "Cloud base" },
            { 3, "Cloud top" },
            { 4, "0 degC isotherm" },
            { 6, "Maximum wind level" },
            { 7, "Tropopause" },
            { 100, "Isobaric surface" },
            { 101, "Mean sea level" },
            { 102, "Specific altitude above mean sea level" },
            { 103, "Height above ground" },
            { 104, "Sigma level" },
            { 105, "Hybrid level" },
            { 106, "Depth below land surface" },
            { 108, "Level at specified pressure difference from ground" },
            { 109, "Potential vorticity surface" },
            { 200, "Entire atmosphere" },
            { 220, "Planetary boundary layer" },
        };

        private static readonly Dictionary<int, string> Centers = new Dictionary<int, string>
        {
            { 7, "US NCEP" },
            { 8, "US NWSTG" },
            { 9, "US other" },
            { 98, "ECMWF" },
        };

        public static (string name, string units) Parameter(int discipline, int category, int number)
        {
            if (Params.TryGetValue((discipline, category, number), out var v))
                return v;
            return ($"disc{discipline}/cat{category}/num{number}", "unknown");
        }

        public static string DisciplineDescription(int discipline)
            => Disciplines.TryGetValue(discipline, out var d) ? d : $"discipline {discipline}";

        public static string CategoryDescription(int discipline, int category)
            => Categories.TryGetValue((discipline, category), out var c) ? c : $"category {category}";

        public static string ProductDefinitionTemplateDescription(int template)
            => ProductTemplates.TryGetValue(template, out var t) ? t : $"PDT {template}";

        public static string LevelDescription(int levelType)
            => Levels.TryGetValue(levelType, out var d) ? d : $"level type {levelType}";

        public static string Center(int centerId)
            => Centers.TryGetValue(centerId, out var c) ? c : $"center {centerId}";

        public static (int discipline, int category, int number) ParameterCode(Model.Parameter parameter)
        {
            int v = (int)parameter;
            return (v / 1_000_000, (v / 1_000) % 1_000, v % 1_000);
        }

        public static Model.Parameter? ToParameter(int discipline, int category, int number)
        {
            int encoded = discipline * 1_000_000 + category * 1_000 + number;
            if (System.Enum.IsDefined(typeof(Model.Parameter), encoded))
                return (Model.Parameter)encoded;
            return null;
        }

        public static Model.LevelType? ToLevelType(int levelTypeCode)
        {
            if (System.Enum.IsDefined(typeof(Model.LevelType), levelTypeCode))
                return (Model.LevelType)levelTypeCode;
            return null;
        }

        public static Model.Discipline? ToDiscipline(int discipline)
        {
            if (System.Enum.IsDefined(typeof(Model.Discipline), discipline))
                return (Model.Discipline)discipline;
            return null;
        }

        public static Model.ProductDefinitionTemplate? ToProductDefinitionTemplate(int template)
        {
            if (System.Enum.IsDefined(typeof(Model.ProductDefinitionTemplate), template))
                return (Model.ProductDefinitionTemplate)template;
            return null;
        }
    }
}
